-- Jalankan di Supabase SQL Editor SEBELUM pakai tombol "Harga" per kategori.
-- Tabel baru untuk harga jual tingkat KATEGORI (dipakai Reseller & Offline saja).
-- channel_harga (harga per toko) TIDAK diubah.

CREATE TABLE IF NOT EXISTS channel_kategori_harga (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori   TEXT    NOT NULL,          -- reseller | offline
  katalog    TEXT    NOT NULL,
  harga_jual NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (kategori, katalog)
);

-- Samakan RLS/policy dengan tabel channel_harga. Kalau channel_harga pakai policy "allow all":
ALTER TABLE channel_kategori_harga ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow all" ON channel_kategori_harga FOR ALL USING (true) WITH CHECK (true);
